function ZoomControl(controlDiv, map) {
  // Creating divs & styles for custom zoom control
  controlDiv.style.padding = '10px';

  // Set CSS for the control wrapper
  var controlWrapper = document.createElement('div');
  controlWrapper.style.backgroundColor = 'transparent';
  controlWrapper.style.borderStyle = 'solid';
  controlWrapper.style.borderWidth = '0';
  controlWrapper.style.cursor = 'pointer';
  controlWrapper.style.textAlign = 'center';
  controlWrapper.style.width = '34px';
  controlWrapper.style.height = '75px';
  controlDiv.appendChild(controlWrapper);

  // Set CSS for the zoomIn
  var zoomInButton = document.createElement('div');
  zoomInButton.style.width = '34px';
  zoomInButton.style.height = '39px';
  zoomInButton.style.backgroundImage = 'url("/themes/custom/dnb/img/icon/controlzoomin.svg")';
  controlWrapper.appendChild(zoomInButton);

  // Set CSS for the zoomOut
  var zoomOutButton = document.createElement('div');
  zoomOutButton.style.width = '34px';
  zoomOutButton.style.height = '36px';
  zoomOutButton.style.backgroundImage = 'url("/themes/custom/dnb/img/icon/controlzoomout.svg")';
  controlWrapper.appendChild(zoomOutButton);

  google.maps.event.addDomListener(zoomInButton, 'click', function() {
    map.setZoom(map.getZoom() + 1);
  });

  google.maps.event.addDomListener(zoomOutButton, 'click', function() {
    map.setZoom(map.getZoom() - 1);
  });

}


var sitesData = [
  {
      "Rollout_Batch": "Batch 1",
      "Onboarding_Batch": "Batch 1-1 109",
      "Priority": "",
      "Nominal_ID": "KUL_172",
      "Site_ID": "DWKUL0091",
      "Site_Name": "DWKUL0091_BALAIISLAM",
      "Latitude": "3.173082",
      "Longitude": "101.691078",
      "Site_Owner": "Digi",
      "Existing_New": "Existing",

  },
  {
      "Rollout_Batch": "Batch 2-2",
      "Onboarding_Batch": "Batch 1-2a",
      "Priority": "Priority 1",
      "Nominal_ID": "KUL_667",
      "Site_ID": "DWKUL0452",
      "Site_Name": "DWKUL0452_DESABUSINESSPARK",
      "Latitude": "3.09822",
      "Longitude": "101.67839",
      "Site_Owner": "edotco",
      "Existing_New": "Existing",

  },
  {
      "Rollout_Batch": "Batch 2-2",
      "Onboarding_Batch": "Batch 1-2a",
      "Priority": "Priority 1",
      "Nominal_ID": "KUL_676",
      "Site_ID": "DWKUL0459",
      "Site_Name": "DWKUL0459_ANTAHTOWER",
      "Latitude": "3.17989",
      "Longitude": "101.67345",
      "Site_Owner": "OCK",
      "Existing_New": "Existing",

  },
  {
      "Rollout_Batch": "Batch 2-2",
      "Onboarding_Batch": "Batch 1-2a",
      "Priority": "Priority 1",
      "Nominal_ID": "KUL_332",
      "Site_ID": "DWKUL0222",
      "Site_Name": "DWKUL0222_PENINSULARRESIDENSI",
      "Latitude": "3.15065",
      "Longitude": "101.66996",
      "Site_Owner": "Digi",
      "Existing_New": "Existing",

  },
  {
      "Rollout_Batch": "Batch 2-1",
      "Onboarding_Batch": "Batch 1-2a",
      "Priority": "Priority 1",
      "Nominal_ID": "KUL_480",
      "Site_ID": "DWKUL0328",
      "Site_Name": "DWKUL0328_BDRTSKSELATAN",
      "Latitude": "3.077729",
      "Longitude": "101.71526",
      "Site_Owner": "Stealth",
      "Existing_New": "Existing",

  },
  {
      "Rollout_Batch": "Batch 2-2",
      "Onboarding_Batch": "Batch 1-2a",
      "Priority": "Priority 1",
      "Nominal_ID": "KUL_496",
      "Site_ID": "DWKUL0341",
      "Site_Name": "DWKUL0341_JLNPANTAIJAYA",
      "Latitude": "3.11533",
      "Longitude": "101.6668",
      "Site_Owner": "EdgePoint",
      "Existing_New": "Existing",

  },
  {
      "Rollout_Batch": "Batch 2-2",
      "Onboarding_Batch": "Batch 1-2a",
      "Priority": "Priority 1",
      "Nominal_ID": "KUL_900",
      "Site_ID": "DWKUL0629",
      "Site_Name": "DWKUL0629_BATU4JLNKELANGLAMA",
      "Latitude": "3.095161",
      "Longitude": "101.675634",
      "Site_Owner": "Edotco",
      "Existing_New": "New",

  },
  {
      "Rollout_Batch": "Batch 2-2",
      "Onboarding_Batch": "Batch 1-2a",
      "Priority": "Priority 1",
      "Nominal_ID": "PJY_65",
      "Site_ID": "DWPPJ0899",
      "Site_Name": "DWPPJ0899_PRSNT19PUTRAJAYA",
      "Latitude": "2.90671",
      "Longitude": "101.69318",
      "Site_Owner": "EdgePoint",
      "Existing_New": "Existing",

  },
  {
      "Rollout_Batch": "Batch 2-2",
      "Onboarding_Batch": "Batch 1-2a",
      "Priority": "Priority 1",
      "Nominal_ID": "KUL_123",
      "Site_ID": "DWKUL0053",
      "Site_Name": "DWKUL0053_PSRNTUANKUJA'AFAR",
      "Latitude": "3.14718",
      "Longitude": "101.6814",
      "Site_Owner": "EdgePoint",
      "Existing_New": "Existing",

  },
  {
      "Rollout_Batch": "Batch 2-2",
      "Onboarding_Batch": "Batch 1-2a",
      "Priority": "Priority 1",
      "Nominal_ID": "KUL_609",
      "Site_ID": "DWKUL0415",
      "Site_Name": "DWKUL0415_JLNLEDANG",
      "Latitude": "3.148269",
      "Longitude": "101.677708",
      "Site_Owner": "edotco",
      "Existing_New": "New",

  },
  {
      "Rollout_Batch": "Batch 2-2",
      "Onboarding_Batch": "Batch 1-2a",
      "Priority": "Priority 1",
      "Nominal_ID": "KUL_149",
      "Site_ID": "DWKUL0074",
      "Site_Name": "DWKUL0074_POSBESAR",
      "Latitude": "3.14363",
      "Longitude": "101.69392",
      "Site_Owner": "edotco",
      "Existing_New": "Existing",

  },
  {
      "Rollout_Batch": "Batch 2-3",
      "Onboarding_Batch": "Batch 1-2b",
      "Priority": "Priority 2",
      "Nominal_ID": "KUL_235",
      "Site_ID": "DWKUL0143",
      "Site_Name": "DWKUL0143_BUKITJALILBUSSPARK",
      "Latitude": "3.062766",
      "Longitude": "101.664398",
      "Site_Owner": "TM",
      "Existing_New": "Existing",

  },
  {
      "Rollout_Batch": "Batch 2-3",
      "Onboarding_Batch": "Batch 1-2b",
      "Priority": "Priority 2",
      "Nominal_ID": "KUL_801",
      "Site_ID": "DWKUL0526",
      "Site_Name": "DWKUL0526_YAYASANTUNRAZAK",
      "Latitude": "3.148303",
      "Longitude": "101.719173",
      "Site_Owner": "TM",
      "Existing_New": "Existing",

  },
  {
      "Rollout_Batch": "Batch 2-3",
      "Onboarding_Batch": "Batch 1-2b",
      "Priority": "Priority 2",
      "Nominal_ID": "KUL_243",
      "Site_ID": "DWKUL0150",
      "Site_Name": "DWKUL0150_JLNPENEGA",
      "Latitude": "3.1408",
      "Longitude": "101.6667",
      "Site_Owner": "Digi",
      "Existing_New": "Existing",

  },
  {
      "Rollout_Batch": "Batch 2-3",
      "Onboarding_Batch": "Batch 1-2b",
      "Priority": "Priority 2",
      "Nominal_ID": "KUL_367",
      "Site_ID": "DWKUL0247",
      "Site_Name": "DWKUL0247_TMNKAYA",
      "Latitude": "3.19013",
      "Longitude": "101.68966",
      "Site_Owner": "Digi",
      "Existing_New": "Existing",

  },
  {
      "Rollout_Batch": "Batch 2-3",
      "Onboarding_Batch": "Batch 1-2b",
      "Priority": "Priority 2",
      "Nominal_ID": "KUL_680",
      "Site_ID": "DWKUL0463",
      "Site_Name": "DWKUL0463_JLNSENTULRIA1",
      "Latitude": "3.19496",
      "Longitude": "101.69048",
      "Site_Owner": "Digi",
      "Existing_New": "Existing",

  },
  {
      "Rollout_Batch": "Batch 2-3",
      "Onboarding_Batch": "Batch 1-2b",
      "Priority": "Priority 2",
      "Nominal_ID": "KUL_797",
      "Site_ID": "DWKUL0522",
      "Site_Name": "DWKUL0522_MONORAILHANGTUAH",
      "Latitude": "3.140761",
      "Longitude": "101.706207",
      "Site_Owner": "VBT",
      "Existing_New": "Existing",

  },
  {
      "Rollout_Batch": "Batch 2-3",
      "Onboarding_Batch": "Batch 1-2b",
      "Priority": "Priority 2",
      "Nominal_ID": "KUL_1008",
      "Site_ID": "DWKUL0010",
      "Site_Name": "DWKUL0010_JLNHANDALAN",
      "Latitude": "3.181944",
      "Longitude": "101.731227",
      "Site_Owner": "Riyyalcomm",
      "Existing_New": "Existing",

  },
  {
      "Rollout_Batch": "Batch 2-3",
      "Onboarding_Batch": "Batch 1-2b",
      "Priority": "Priority 2",
      "Nominal_ID": "KUL_23",
      "Site_ID": "DWKUL0139",
      "Site_Name": "DWKUL0139_TMNMIHARJA",
      "Latitude": "3.123037",
      "Longitude": "101.722235",
      "Site_Owner": "Digi",
      "Existing_New": "Existing",

  },
  {
      "Rollout_Batch": "Batch 2-3",
      "Onboarding_Batch": "Batch 1-2b",
      "Priority": "Priority 2",
      "Nominal_ID": "KUL_210",
      "Site_ID": "DWKUL0122",
      "Site_Name": "DWKUL0122_TMNDANAUKOTA3",
      "Latitude": "3.202112",
      "Longitude": "101.720941",
      "Site_Owner": "Digi",
      "Existing_New": "Existing",

  },
  {
      "Rollout_Batch": "Batch 2-3",
      "Onboarding_Batch": "Batch 1-2b",
      "Priority": "Priority 2",
      "Nominal_ID": "SGR_1939",
      "Site_ID": "DWKUL0746",
      "Site_Name": "DWKUL0746_TMNSRIMURNI",
      "Latitude": "3.2347",
      "Longitude": "101.663142",
      "Site_Owner": "TM",
      "Existing_New": "Existing",

  },
  {
      "Rollout_Batch": "Batch 2-3",
      "Onboarding_Batch": "Batch 1-2b",
      "Priority": "Priority 2",
      "Nominal_ID": "Site10393",
      "Site_ID": "DBSEP1869",
      "Site_Name": "DBSEP1869_TMONEKVDC",
      "Latitude": "2.932499",
      "Longitude": "101.657365",
      "Site_Owner": "TM",
      "Existing_New": "Existing",

  },
  {
      "Rollout_Batch": "Batch 2-3",
      "Onboarding_Batch": "Batch 1-2b",
      "Priority": "Priority 2",
      "Nominal_ID": "KUL_930",
      "Site_ID": "DWKUL0661",
      "Site_Name": "DWKUL0661_SMKDESAPERDANA",
      "Latitude": "3.106329",
      "Longitude": "101.689779",
      "Site_Owner": "Edotco",
      "Existing_New": "New",

  },
  {
      "Rollout_Batch": "Batch 2-3",
      "Onboarding_Batch": "Batch 1-2b",
      "Priority": "Priority 2",
      "Nominal_ID": "KUL_184",
      "Site_ID": "DWKUL0100",
      "Site_Name": "DWKUL0100_BGSRHEIGTHCONDO",
      "Latitude": "3.123879",
      "Longitude": "101.671203",
      "Site_Owner": "Digi",
      "Existing_New": "Existing",

  },
  {
      "Rollout_Batch": "Batch 2-3",
      "Onboarding_Batch": "Batch 1-2b",
      "Priority": "Priority 2",
      "Nominal_ID": "KUL_427",
      "Site_ID": "DWKUL0292",
      "Site_Name": "DWKUL0292_TMNTENAGA",
      "Latitude": "3.114227",
      "Longitude": "101.723036",
      "Site_Owner": "edotco",
      "Existing_New": "Existing",

  },
  {
      "Rollout_Batch": "Batch 2-3",
      "Onboarding_Batch": "Batch 1-2b",
      "Priority": "Priority 2",
      "Nominal_ID": "KUL_384",
      "Site_ID": "DWKUL0263",
      "Site_Name": "DWKUL0263_SEK2WANGSAMAJU",
      "Latitude": "3.21008",
      "Longitude": "101.73167",
      "Site_Owner": "edotco",
      "Existing_New": "Existing",

  },
  {
      "Rollout_Batch": "Batch 2-3",
      "Onboarding_Batch": "Batch 1-2b",
      "Priority": "Priority 2",
      "Nominal_ID": "KUL_284",
      "Site_ID": "DWKUL0180",
      "Site_Name": "DWKUL0180_MSJDSALAHUDDIN",
      "Latitude": "3.2225",
      "Longitude": "101.719868",
      "Site_Owner": "Stealth",
      "Existing_New": "Existing",

  },
  {
      "Rollout_Batch": "Batch 2-3",
      "Onboarding_Batch": "Batch 1-2b",
      "Priority": "Priority 2",
      "Nominal_ID": "SGR_721",
      "Site_ID": "DBSEP1836",
      "Site_Name": "DBSEP1836_PSRNSEMARAKAPI",
      "Latitude": "2.9302575",
      "Longitude": "101.6477159",
      "Site_Owner": "Argus Intan",
      "Existing_New": "New",

  },
  {
      "Rollout_Batch": "Batch 2-3",
      "Onboarding_Batch": "Batch 1-2b",
      "Priority": "Priority 2",
      "Nominal_ID": "KUL_891",
      "Site_ID": "DWKUL0618",
      "Site_Name": "DWKUL0618_TMNOUG",
      "Latitude": "3.07225",
      "Longitude": "101.672861",
      "Site_Owner": "TM",
      "Existing_New": "Existing",

  },
  {
      "Rollout_Batch": "Batch 2-3",
      "Onboarding_Batch": "Batch 1-2b",
      "Priority": "Priority 2",
      "Nominal_ID": "KUL_398",
      "Site_ID": "DWKUL0273",
      "Site_Name": "DWKUL0273_JLNBESARKEPONG",
      "Latitude": "3.2139",
      "Longitude": "101.63538",
      "Site_Owner": "Digi",
      "Existing_New": "Existing",

  },
  {
      "Rollout_Batch": "Batch 2-3",
      "Onboarding_Batch": "Batch 1-2b",
      "Priority": "Priority 2",
      "Nominal_ID": "KUL_481",
      "Site_ID": "DWKUL0329",
      "Site_Name": "DWKUL0329_JLNDSARA",
      "Latitude": "3.13343",
      "Longitude": "101.6346",
      "Site_Owner": "Edotco",
      "Existing_New": "Existing",

  },
  {
      "Rollout_Batch": "Batch 2-3",
      "Onboarding_Batch": "Batch 1-2b",
      "Priority": "Priority 2",
      "Nominal_ID": "KUL_389",
      "Site_ID": "DWKUL0265",
      "Site_Name": "DWKUL0265_SRIRAMPAI",
      "Latitude": "3.197875",
      "Longitude": "101.737901",
      "Site_Owner": "edotco",
      "Existing_New": "New",

  },
  {
      "Rollout_Batch": "Batch 2-3",
      "Onboarding_Batch": "Batch 1-2b",
      "Priority": "Priority 2",
      "Nominal_ID": "KUL_499",
      "Site_ID": "DWKUL0343",
      "Site_Name": "DWKUL0343_TMNAYERPANAS",
      "Latitude": "3.187935",
      "Longitude": "101.72333",
      "Site_Owner": "edotco",
      "Existing_New": "New",

  },
  {
      "Rollout_Batch": "Batch 2-3",
      "Onboarding_Batch": "Batch 1-2b",
      "Priority": "Priority 2",
      "Nominal_ID": "SGR_1723",
      "Site_ID": "DWKUL0742",
      "Site_Name": "DWKUL0742_TMNWLYHSELAYANG",
      "Latitude": "3.237597",
      "Longitude": "101.659952",
      "Site_Owner": "edotco",
      "Existing_New": "New",

  },
  {
      "Rollout_Batch": "Batch 2-3",
      "Onboarding_Batch": "Batch 1-2b",
      "Priority": "Priority 2",
      "Nominal_ID": "SGR_835",
      "Site_ID": "DBSEP1841",
      "Site_Name": "DBSEP1841_ CENTURYSQUARE",
      "Latitude": "2.924451",
      "Longitude": "101.660779",
      "Site_Owner": "edotco",
      "Existing_New": "Existing",

  },
  {
      "Rollout_Batch": "Batch 2-3",
      "Onboarding_Batch": "Batch 1-2b",
      "Priority": "Priority 2",
      "Nominal_ID": "KUL_262",
      "Site_ID": "DWKUL0163",
      "Site_Name": "DWKUL0163_JLNMANIS",
      "Latitude": "3.090027",
      "Longitude": "101.74363",
      "Site_Owner": "Digi",
      "Existing_New": "Existing",

  },
  {
      "Rollout_Batch": "Batch 2-3",
      "Onboarding_Batch": "Batch 1-2b",
      "Priority": "Priority 2",
      "Nominal_ID": "KUL_647",
      "Site_ID": "DWKUL0438",
      "Site_Name": "DWKUL0438_JLNLAKSAMANA",
      "Latitude": "3.178411",
      "Longitude": "101.723809",
      "Site_Owner": "Riyyalcomm",
      "Existing_New": "Existing",

  },
  {
      "Rollout_Batch": "Batch 2-3",
      "Onboarding_Batch": "Batch 1-2b",
      "Priority": "Priority 2",
      "Nominal_ID": "KUL_722",
      "Site_ID": "DWKUL0492",
      "Site_Name": "DWKUL0492_UTMJLNSEMARAK",
      "Latitude": "3.175024",
      "Longitude": "101.721134",
      "Site_Owner": "edotco",
      "Existing_New": "Existing",

  },
  {
      "Rollout_Batch": "Batch 2-3",
      "Onboarding_Batch": "Batch 1-2b",
      "Priority": "Priority 2",
      "Nominal_ID": "KUL_24",
      "Site_ID": "DWKUL0148",
      "Site_Name": "DWKUL0148_MENARAHAWPAR",
      "Latitude": "3.154523",
      "Longitude": "101.706071",
      "Site_Owner": "Digi",
      "Existing_New": "Existing",

  },
  {
      "Rollout_Batch": "Batch 2-3",
      "Onboarding_Batch": "Batch 1-2b",
      "Priority": "Priority 2",
      "Nominal_ID": "KUL_225",
      "Site_ID": "DWKUL0135",
      "Site_Name": "DWKUL0135_PSRNPRIMAPELANGI",
      "Latitude": "3.176002",
      "Longitude": "101.65053",
      "Site_Owner": "edotco",
      "Existing_New": "New",

  },
  {
      "Rollout_Batch": "Batch 2-3",
      "Onboarding_Batch": "Batch 1-2b",
      "Priority": "Priority 2",
      "Nominal_ID": "KUL_721",
      "Site_ID": "DWKUL0491",
      "Site_Name": "DWKUL0491_JLNTUNRAZAK",
      "Latitude": "3.173078",
      "Longitude": "101.70456",
      "Site_Owner": "edotco",
      "Existing_New": "New",

  },
  {
      "Rollout_Batch": "Batch 2-3",
      "Onboarding_Batch": "Batch 1-2b",
      "Priority": "Priority 2",
      "Nominal_ID": "KUL_447",
      "Site_ID": "DWKUL0305",
      "Site_Name": "DWKUL0305_TMNTUNDRISMAIL",
      "Latitude": "3.149498",
      "Longitude": "101.630394",
      "Site_Owner": "edotco",
      "Existing_New": "New",

  },
  {
      "Rollout_Batch": "Batch 2-3",
      "Onboarding_Batch": "Batch 1-2b",
      "Priority": "Priority 2",
      "Nominal_ID": "KUL_886",
      "Site_ID": "DWKUL0613",
      "Site_Name": "DWKUL0613_JLNARABNGSAR",
      "Latitude": "3.130398",
      "Longitude": "101.666905",
      "Site_Owner": "Edotco",
      "Existing_New": "New",

  },
  {
      "Rollout_Batch": "Batch 2-3",
      "Onboarding_Batch": "Batch 1-2b",
      "Priority": "Priority 2",
      "Nominal_ID": "KUL_18",
      "Site_ID": "DWKUL0097",
      "Site_Name": "DWKUL0097_LORONGMERANTI",
      "Latitude": "3.137407",
      "Longitude": "101.70783",
      "Site_Owner": "Digi",
      "Existing_New": "Existing",

  },
  {
      "Rollout_Batch": "Batch 2-3",
      "Onboarding_Batch": "Batch 1-2b",
      "Priority": "Priority 2",
      "Nominal_ID": "KUL_704",
      "Site_ID": "DWKUL0481",
      "Site_Name": "DWKUL0481_KLGCC",
      "Latitude": "3.1386",
      "Longitude": "101.6403",
      "Site_Owner": "edotco",
      "Existing_New": "Existing",

  },
  {
      "Rollout_Batch": "Batch 2-3",
      "Onboarding_Batch": "Batch 1-2b",
      "Priority": "Priority 2",
      "Nominal_ID": "KUL_638",
      "Site_ID": "DWKUL0429",
      "Site_Name": "DWKUL0429_LRTABDULLAHHUKUM",
      "Latitude": "3.119096",
      "Longitude": "101.673003",
      "Site_Owner": "VBT",
      "Existing_New": "Existing",

  },
  {
      "Rollout_Batch": "Batch 2-3",
      "Onboarding_Batch": "Batch 1-2b",
      "Priority": "Priority 2",
      "Nominal_ID": "KUL_1004",
      "Site_ID": "DWKUL0006",
      "Site_Name": "DWKUL0006_JLNMENARAGADING1",
      "Latitude": "3.08094",
      "Longitude": "101.73222",
      "Site_Owner": "TM",
      "Existing_New": "Existing",

  },
  {
      "Rollout_Batch": "Batch 2-3",
      "Onboarding_Batch": "Batch 1-2b",
      "Priority": "Priority 2",
      "Nominal_ID": "KUL_319",
      "Site_ID": "DWKUL0214",
      "Site_Name": "DWKUL0214_WTDESAPARKCITY",
      "Latitude": "3.187542",
      "Longitude": "101.623015",
      "Site_Owner": "GTP",
      "Existing_New": "Existing",

  },
  {
      "Rollout_Batch": "Batch 2-3",
      "Onboarding_Batch": "Batch 1-2b",
      "Priority": "Priority 2",
      "Nominal_ID": "SGR_1192",
      "Site_ID": "DWKUL0740",
      "Site_Name": "DWKUL0740_TMNKPSPLSFASA",
      "Latitude": "3.221416",
      "Longitude": "101.690871",
      "Site_Owner": "TM",
      "Existing_New": "Existing",

  },
  {
      "Rollout_Batch": "Batch 2-3",
      "Onboarding_Batch": "Batch 1-2b",
      "Priority": "Priority 2",
      "Nominal_ID": "Site10390",
      "Site_ID": "DBSEP1866",
      "Site_Name": "DBSEP1866_CYBERJAYA",
      "Latitude": "2.911698",
      "Longitude": "101.650908",
      "Site_Owner": "Argus Intan",
      "Existing_New": "New",

  },
  {
      "Rollout_Batch": "Batch 2-3",
      "Onboarding_Batch": "Batch 1-2b",
      "Priority": "Priority 2",
      "Nominal_ID": "KUL_495",
      "Site_ID": "DWKUL0340",
      "Site_Name": "DWKUL0340_LBHRAYAKUL-SBN",
      "Latitude": "3.058099",
      "Longitude": "101.704958",
      "Site_Owner": "OCK",
      "Existing_New": "Existing",

  },
  {
      "Rollout_Batch": "Batch 2-3",
      "Onboarding_Batch": "Batch 1-2b",
      "Priority": "Priority 2",
      "Nominal_ID": "KUL_829",
      "Site_ID": "DWKUL0555",
      "Site_Name": "DWKUL0555_JLNDESAUTAMA1",
      "Latitude": "3.108608",
      "Longitude": "101.688231",
      "Site_Owner": "Edotco",
      "Existing_New": "New",

  },
  {
      "Rollout_Batch": "Batch 2-3",
      "Onboarding_Batch": "Batch 1-2b",
      "Priority": "Priority 2",
      "Nominal_ID": "KUL_68",
      "Site_ID": "DWKUL0462",
      "Site_Name": "DWKUL0462_LRTBANDARAYA",
      "Latitude": "3.15556",
      "Longitude": "101.69444",
      "Site_Owner": "VBT",
      "Existing_New": "Existing",

  },
  {
      "Rollout_Batch": "Batch 2-3",
      "Onboarding_Batch": "Batch 1-2b",
      "Priority": "Priority 2",
      "Nominal_ID": "KUL_263",
      "Site_ID": "DWKUL0164",
      "Site_Name": "DWKUL0164_TamanMidah",
      "Latitude": "3.100426",
      "Longitude": "101.728483",
      "Site_Owner": "Edotco",
      "Existing_New": "New",

  },
  {
      "Rollout_Batch": "Batch 2-3",
      "Onboarding_Batch": "Batch 1-2b",
      "Priority": "Priority 2",
      "Nominal_ID": "KUL_97",
      "Site_ID": "DWKUL0703",
      "Site_Name": "DWKUL0703_JLNPUNCAKSETIAWANGSA4",
      "Latitude": "3.188797",
      "Longitude": "101.74381",
      "Site_Owner": "Digi",
      "Existing_New": "Existing",

  },
  {
      "Rollout_Batch": "Batch 2-3",
      "Onboarding_Batch": "Batch 1-2b",
      "Priority": "Priority 2",
      "Nominal_ID": "KUL_292",
      "Site_ID": "DWKUL0188",
      "Site_Name": "DWKUL0188_KEMSGBESI2",
      "Latitude": "3.07415",
      "Longitude": "101.72076",
      "Site_Owner": "NFS",
      "Existing_New": "Existing",

  },
  {
      "Rollout_Batch": "Batch 2-3",
      "Onboarding_Batch": "Batch 1-2b",
      "Priority": "Priority 2",
      "Nominal_ID": "KUL_703",
      "Site_ID": "DWKUL0480",
      "Site_Name": "DWKUL0480_JLN109FTMNDANAUDESA",
      "Latitude": "3.101014",
      "Longitude": "101.688974",
      "Site_Owner": "edotco",
      "Existing_New": "New",

  },
  {
      "Rollout_Batch": "Batch 2-3",
      "Onboarding_Batch": "Batch 1-2b",
      "Priority": "Priority 2",
      "Nominal_ID": "KUL_216",
      "Site_ID": "DWKUL0128",
      "Site_Name": "DWKUL0128_JLNKGPANDAN2",
      "Latitude": "3.143693",
      "Longitude": "101.728663",
      "Site_Owner": "Digi",
      "Existing_New": "Existing",

  },
  {
      "Rollout_Batch": "Batch 2-3",
      "Onboarding_Batch": "Batch 1-2b",
      "Priority": "Priority 2",
      "Nominal_ID": "KUL_260",
      "Site_ID": "DWKUL0161",
      "Site_Name": "DWKUL0161_SYABASDesaParkCity",
      "Latitude": "3.1811333",
      "Longitude": "101.636627",
      "Site_Owner": "EdgePoint",
      "Existing_New": "Existing",

  },
  {
      "Rollout_Batch": "Batch 2-3",
      "Onboarding_Batch": "Batch 1-2b",
      "Priority": "Priority 2",
      "Nominal_ID": "KUL_968",
      "Site_ID": "DWKUL0701",
      "Site_Name": "DWKUL0701_SURAUALAMIN",
      "Latitude": "3.08563",
      "Longitude": "101.71541",
      "Site_Owner": "Teleflow",
      "Existing_New": "Existing",

  },
  {
      "Rollout_Batch": "Batch 2-3",
      "Onboarding_Batch": "Batch 1-2b",
      "Priority": "Priority 2",
      "Nominal_ID": "KUL_787",
      "Site_ID": "DWKUL0512",
      "Site_Name": "DWKUL0512_JLNSETIAMURNI6",
      "Latitude": "3.152701",
      "Longitude": "101.650843",
      "Site_Owner": "Edotco",
      "Existing_New": "New",

  },
  {
      "Rollout_Batch": "Batch 2-3",
      "Onboarding_Batch": "Batch 1-2b",
      "Priority": "Priority 2",
      "Nominal_ID": "KUL_452",
      "Site_ID": "DWKUL0309",
      "Site_Name": "DWKUL0309_JLNJALILJAYA",
      "Latitude": "3.05755",
      "Longitude": "101.67405",
      "Site_Owner": "Digi",
      "Existing_New": "Existing",

  },
  {
      "Rollout_Batch": "Batch 2-3",
      "Onboarding_Batch": "Batch 1-2b",
      "Priority": "Priority 2",
      "Nominal_ID": "KUL_316",
      "Site_ID": "DWKUL0211",
      "Site_Name": "DWKUL0211_TMNPRIMAIMPIAN",
      "Latitude": "3.18331",
      "Longitude": "101.64573",
      "Site_Owner": "OCK",
      "Existing_New": "Existing",

  },
  {
      "Rollout_Batch": "Batch 2-3",
      "Onboarding_Batch": "Batch 1-2b",
      "Priority": "Priority 2",
      "Nominal_ID": "PJY_16",
      "Site_ID": "DWPPJ0821",
      "Site_Name": "DWPPJ0821_PULSEGRANDEHOTEL",
      "Latitude": "2.942951",
      "Longitude": "101.699883",
      "Site_Owner": "edotco",
      "Existing_New": "Existing",

  },
  {
      "Rollout_Batch": "Batch 2-3",
      "Onboarding_Batch": "Batch 1-2b",
      "Priority": "Priority 2",
      "Nominal_ID": "KUL_401",
      "Site_ID": "DWKUL0276",
      "Site_Name": "DWKUL0276_245MAINSTREET",
      "Latitude": "3.09683",
      "Longitude": "101.69576",
      "Site_Owner": "OCK",
      "Existing_New": "Existing",

  },
  {
      "Rollout_Batch": "Batch 2-3",
      "Onboarding_Batch": "Batch 1-2b",
      "Priority": "Priority 2",
      "Nominal_ID": "KUL_298",
      "Site_ID": "DWKUL0194",
      "Site_Name": "DWKUL0194_UPNM",
      "Latitude": "3.046774",
      "Longitude": "101.722198",
      "Site_Owner": "NFS",
      "Existing_New": "Existing",

  },
  {
      "Rollout_Batch": "Batch 2-3",
      "Onboarding_Batch": "Batch 1-2b",
      "Priority": "Priority 2",
      "Nominal_ID": "KUL_386",
      "Site_ID": "DWKUL0264",
      "Site_Name": "DWKUL0264_WLYHPERSEKUTAN",
      "Latitude": "3.1333",
      "Longitude": "101.684372",
      "Site_Owner": "edotco",
      "Existing_New": "Existing",

  },
  {
      "Rollout_Batch": "Batch 2-3",
      "Onboarding_Batch": "Batch 1-2b",
      "Priority": "Priority 2",
      "Nominal_ID": "KUL_490",
      "Site_ID": "DWKUL0337",
      "Site_Name": "DWKUL0337_JLNMELATIUTAMA1",
      "Latitude": "3.220666",
      "Longitude": "101.730389",
      "Site_Owner": "edotco",
      "Existing_New": "New",

  },
  {
      "Rollout_Batch": "Batch 2-3",
      "Onboarding_Batch": "Batch 1-2b",
      "Priority": "Priority 2",
      "Nominal_ID": "KUL_1022",
      "Site_ID": "DWKUL0026",
      "Site_Name": "DWKUL0026_ROYALSELANGORPOLOCLUB",
      "Latitude": "3.15386",
      "Longitude": "101.74096",
      "Site_Owner": "EdgePoint",
      "Existing_New": "Existing",

  },
  {
      "Rollout_Batch": "Batch 2-3",
      "Onboarding_Batch": "Batch 1-2b",
      "Priority": "Priority 2",
      "Nominal_ID": "KUL_351",
      "Site_ID": "DWKUL0239",
      "Site_Name": "DWKUL0239_AXAREBKTJALIL",
      "Latitude": "3.05319",
      "Longitude": "101.69559",
      "Site_Owner": "Digi",
      "Existing_New": "Existing",

  },
  {
      "Rollout_Batch": "Batch 2-3",
      "Onboarding_Batch": "Batch 1-2b",
      "Priority": "Priority 2",
      "Nominal_ID": "KUL_847",
      "Site_ID": "DWKUL0573",
      "Site_Name": "DWKUL0573_JLNLANGPERUTPUTIH",
      "Latitude": "3.188634",
      "Longitude": "101.647954",
      "Site_Owner": "Edotco",
      "Existing_New": "New",

  },
  {
      "Rollout_Batch": "Batch 2-3",
      "Onboarding_Batch": "Batch 1-2b",
      "Priority": "Priority 2",
      "Nominal_ID": "KUL_323",
      "Site_ID": "DWKUL0217",
      "Site_Name": "DWKUL0217_JLNBUDIMAN7",
      "Latitude": "3.087953",
      "Longitude": "101.71828",
      "Site_Owner": "EdgePoint",
      "Existing_New": "Existing",

  },
  {
      "Rollout_Batch": "Batch 2-3",
      "Onboarding_Batch": "Batch 1-2b",
      "Priority": "Priority 2",
      "Nominal_ID": "KUL_681",
      "Site_ID": "DWKUL0464",
      "Site_Name": "DWKUL0464_TMNPERINDUSTRIANIKS",
      "Latitude": "3.219977",
      "Longitude": "101.687703",
      "Site_Owner": "edotco",
      "Existing_New": "New",

  },
  {
      "Rollout_Batch": "Batch 2-3",
      "Onboarding_Batch": "Batch 1-2b",
      "Priority": "Priority 2",
      "Nominal_ID": "KUL_878",
      "Site_ID": "DWKUL0605",
      "Site_Name": "DWKUL0605_JLNBTGUTARA",
      "Latitude": "3.225299",
      "Longitude": "101.662425",
      "Site_Owner": "Edotco",
      "Existing_New": "New",

  },
  {
      "Rollout_Batch": "Batch 2-3",
      "Onboarding_Batch": "Batch 1-2b",
      "Priority": "Priority 2",
      "Nominal_ID": "KUL_85",
      "Site_ID": "DWKUL0576",
      "Site_Name": "DWKUL0576_JLNTUNRAZAK2",
      "Latitude": "3.151693",
      "Longitude": "101.722667",
      "Site_Owner": "edotco",
      "Existing_New": "New",

  },
  {
      "Rollout_Batch": "Batch 2-3",
      "Onboarding_Batch": "Batch 1-2b",
      "Priority": "Priority 2",
      "Nominal_ID": "KUL_669",
      "Site_ID": "DWKUL0454",
      "Site_Name": "DWKUL0454_JLNLANGGAKGOLF",
      "Latitude": "3.154657",
      "Longitude": "101.730817",
      "Site_Owner": "edotco",
      "Existing_New": "New",

  },
  {
      "Rollout_Batch": "Batch 2-3",
      "Onboarding_Batch": "Batch 1-2b",
      "Priority": "Priority 2",
      "Nominal_ID": "KUL_964",
      "Site_ID": "DWKUL0697",
      "Site_Name": "DWKUL0697_MJDRAJAIYAH",
      "Latitude": "3.165148",
      "Longitude": "101.710509",
      "Site_Owner": "Edotco",
      "Existing_New": "Existing",

  },
  {
      "Rollout_Batch": "Batch 2-3",
      "Onboarding_Batch": "Batch 1-2b",
      "Priority": "Priority 2",
      "Nominal_ID": "KUL_486",
      "Site_ID": "DWKUL0333",
      "Site_Name": "DWKUL0333_JLNPRIMASETAPAK5",
      "Latitude": "3.198665",
      "Longitude": "101.712751",
      "Site_Owner": "edotco",
      "Existing_New": "New",

  },
  {
      "Rollout_Batch": "Batch 2-3",
      "Onboarding_Batch": "Batch 1-2b",
      "Priority": "Priority 2",
      "Nominal_ID": "KUL_933",
      "Site_ID": "DWKUL0664",
      "Site_Name": "DWKUL0664_JALANMERAHSILU",
      "Latitude": "3.071475",
      "Longitude": "101.694605",
      "Site_Owner": "Edotco",
      "Existing_New": "New",

  },
  {
      "Rollout_Batch": "Batch 2-3",
      "Onboarding_Batch": "Batch 1-2b",
      "Priority": "Priority 2",
      "Nominal_ID": "KUL_871",
      "Site_ID": "DWKUL0598",
      "Site_Name": "DWKUL0598_JLNTMNSERISENTOSA",
      "Latitude": "3.082069",
      "Longitude": "101.660902",
      "Site_Owner": "Edotco",
      "Existing_New": "New",

  },
  {
      "Rollout_Batch": "Batch 2-3",
      "Onboarding_Batch": "Batch 1-2b",
      "Priority": "Priority 2",
      "Nominal_ID": "KUL_899",
      "Site_ID": "DWKUL0626",
      "Site_Name": "DWKUL0626_JALANSEPADU",
      "Latitude": "3.081214",
      "Longitude": "101.676542",
      "Site_Owner": "Edotco",
      "Existing_New": "New",

  },
  {
      "Rollout_Batch": "Batch 2-3",
      "Onboarding_Batch": "Batch 1-2b",
      "Priority": "Priority 2",
      "Nominal_ID": "KUL_2",
      "Site_ID": "DWKUL0113",
      "Site_Name": "DWKUL0113_HUPLEEIMBI",
      "Latitude": "3.1446",
      "Longitude": "101.71538",
      "Site_Owner": "edotco",
      "Existing_New": "Existing",

  },
  {
      "Rollout_Batch": "Batch 2-3",
      "Onboarding_Batch": "Batch 1-2b",
      "Priority": "Priority 2",
      "Nominal_ID": "KUL_860",
      "Site_ID": "DWKUL0587",
      "Site_Name": "DWKUL0587_JALANBESARKEPONG",
      "Latitude": "3.208403",
      "Longitude": "101.653996",
      "Site_Owner": "Edotco",
      "Existing_New": "New",

  },
  {
      "Rollout_Batch": "Batch 2-3",
      "Onboarding_Batch": "Batch 1-2b",
      "Priority": "Priority 2",
      "Nominal_ID": "KUL_976",
      "Site_ID": "DWKUL0710",
      "Site_Name": "DWKUL0710_JLNJELAWAT",
      "Latitude": "3.116704",
      "Longitude": "101.7193",
      "Site_Owner": "Edotco",
      "Existing_New": "New",

  },
  {
      "Rollout_Batch": "Batch 2-3",
      "Onboarding_Batch": "Batch 1-2b",
      "Priority": "Priority 2",
      "Nominal_ID": "KUL_75",
      "Site_ID": "DWKUL0502",
      "Site_Name": "DWKUL0502_JLNTAR",
      "Latitude": "3.151796",
      "Longitude": "101.696057",
      "Site_Owner": "OCK",
      "Existing_New": "Existing",

  },
  {
      "Rollout_Batch": "Batch 2-3",
      "Onboarding_Batch": "Batch 1-2b",
      "Priority": "Priority 2",
      "Nominal_ID": "KUL_130",
      "Site_ID": "DWKUL0059",
      "Site_Name": "DWKUL0059_JALANLANGKAWI",
      "Latitude": "3.055261",
      "Longitude": "101.722747",
      "Site_Owner": "NFS",
      "Existing_New": "Existing",

  },
  {
      "Rollout_Batch": "Batch 4-1",
      "Onboarding_Batch": "Batch 2",
      "Priority": "",
      "Nominal_ID": "KUL_485",
      "Site_ID": "DWKUL0332",
      "Site_Name": "DWKUL0332_BUKITJALIL",
      "Latitude": "3.0549638,",
      "Longitude": "101.688796",
      "Site_Owner": "edotco",
      "Existing_New": "Existing",

  },
  {
      "Rollout_Batch": "Batch 4-1",
      "Onboarding_Batch": "Batch 2",
      "Priority": "",
      "Nominal_ID": "KUL_174",
      "Site_ID": "DWKUL0092",
      "Site_Name": "DWKUL0092_TMNSERANGKAI",
      "Latitude": "3.078402",
      "Longitude": "101.686012",
      "Site_Owner": "edotco",
      "Existing_New": "New",

  },
  {
      "Rollout_Batch": "Batch 4-1",
      "Onboarding_Batch": "Batch 2",
      "Priority": "",
      "Nominal_ID": "KUL_355",
      "Site_ID": "DWKUL0243",
      "Site_Name": "DWKUL0243_PANGSAPURIKASTURI",
      "Latitude": "3.09633",
      "Longitude": "101.7137",
      "Site_Owner": "TM",
      "Existing_New": "Existing",

  },
  {
      "Rollout_Batch": "Batch 4-1",
      "Onboarding_Batch": "Batch 2",
      "Priority": "",
      "Nominal_ID": "KUL_312",
      "Site_ID": "DWKUL0208",
      "Site_Name": "DWKUL0208_JLNNANYANGEST",
      "Latitude": "3.22183",
      "Longitude": "101.66292",
      "Site_Owner": "Digi",
      "Existing_New": "Existing",

  },
  {
      "Rollout_Batch": "Batch 4-1",
      "Onboarding_Batch": "Batch 2",
      "Priority": "",
      "Nominal_ID": "KUL_244",
      "Site_ID": "DBPET1784",
      "Site_Name": "DBPET1784_TECHNOLOGYPARKMALAYSIA",
      "Latitude": "3.04516",
      "Longitude": "101.69057",
      "Site_Owner": "EdgePoint",
      "Existing_New": "Existing",

  },
  {
      "Rollout_Batch": "Batch 4-1",
      "Onboarding_Batch": "Batch 2",
      "Priority": "",
      "Nominal_ID": "KUL_311",
      "Site_ID": "DWKUL0207",
      "Site_Name": "DWKUL0207_WISMAILMU",
      "Latitude": "3.1991",
      "Longitude": "101.62383",
      "Site_Owner": "Digi",
      "Existing_New": "Existing",

  },
  {
      "Rollout_Batch": "Batch 4-1",
      "Onboarding_Batch": "Batch 2",
      "Priority": "",
      "Nominal_ID": "KUL_231",
      "Site_ID": "DWKUL0141",
      "Site_Name": "DWKUL0141_UNIVERSITIMALAYA",
      "Latitude": "3.1185",
      "Longitude": "101.653627",
      "Site_Owner": "edotco",
      "Existing_New": "Existing",

  },
  {
      "Rollout_Batch": "Batch 4-1",
      "Onboarding_Batch": "Batch 2",
      "Priority": "",
      "Nominal_ID": "KUL_501",
      "Site_ID": "DWKUL0345",
      "Site_Name": "DWKUL0345_UNIVERSITIMALAYA1",
      "Latitude": "3.128886",
      "Longitude": "101.660784",
      "Site_Owner": "edotco",
      "Existing_New": "Existing",

  },
  {
      "Rollout_Batch": "Batch 4-1",
      "Onboarding_Batch": "Batch 2",
      "Priority": "",
      "Nominal_ID": "KUL_239",
      "Site_ID": "DWKUL0147",
      "Site_Name": "DWKUL0147_TMNSETAPAKINDAH",
      "Latitude": "3.209807",
      "Longitude": "101.719741",
      "Site_Owner": "Digi",
      "Existing_New": "Existing",

  },
  {
      "Rollout_Batch": "Batch 4-1",
      "Onboarding_Batch": "Batch 2",
      "Priority": "",
      "Nominal_ID": "PJY_38",
      "Site_ID": "DWPPJ0875",
      "Site_Name": "DWPPJ0875_JBTNPRNAMENTERI",
      "Latitude": "2.93651",
      "Longitude": "101.69393",
      "Site_Owner": "Teleflow",
      "Existing_New": "Existing",

  },
  {
      "Rollout_Batch": "Batch 4-1",
      "Onboarding_Batch": "Batch 2",
      "Priority": "",
      "Nominal_ID": "KUL_694",
      "Site_ID": "DWKUL0905",
      "Site_Name": "DWKUL0905_JLNKLGLAMA",
      "Latitude": "3.072514",
      "Longitude": "101.651972",
      "Site_Owner": "edotco",
      "Existing_New": "Existing",

  },
  {
      "Rollout_Batch": "Batch 4-1",
      "Onboarding_Batch": "Batch 2",
      "Priority": "",
      "Nominal_ID": "KUL_238",
      "Site_ID": "DWKUL0146",
      "Site_Name": "DWKUL0146_3GLDNO1FDCRT",
      "Latitude": "3.20168833",
      "Longitude": "101.644845",
      "Site_Owner": "TM",
      "Existing_New": "Existing",

  },
  {
      "Rollout_Batch": "Batch 4-1",
      "Onboarding_Batch": "Batch 2",
      "Priority": "",
      "Nominal_ID": "KUL_881",
      "Site_ID": "DWKUL0608",
      "Site_Name": "DWKUL0608_PANTAIHILLPARK",
      "Latitude": "3.107732",
      "Longitude": "101.663214",
      "Site_Owner": "TM",
      "Existing_New": "Existing",

  },
  {
      "Rollout_Batch": "Batch 4-1",
      "Onboarding_Batch": "Batch 2",
      "Priority": "",
      "Nominal_ID": "SGR_1006",
      "Site_ID": "DBSEP1810",
      "Site_Name": "DBSEP1810_CBD2PSRNMULTIMEDIA",
      "Latitude": "2.926056",
      "Longitude": "101.651167",
      "Site_Owner": "edotco",
      "Existing_New": "Existing",

  },
  {
      "Rollout_Batch": "Batch 4-1",
      "Onboarding_Batch": "Batch 2",
      "Priority": "",
      "Nominal_ID": "KUL_133",
      "Site_ID": "DWKUL0061",
      "Site_Name": "DWKUL0061_TMNUSAHAWAN",
      "Latitude": "3.217013",
      "Longitude": "101.64465",
      "Site_Owner": "TM",
      "Existing_New": "Existing",

  },
  {
      "Rollout_Batch": "Batch 4-1",
      "Onboarding_Batch": "Batch 2",
      "Priority": "",
      "Nominal_ID": "KUL_382",
      "Site_ID": "DWKUL0262",
      "Site_Name": "DWKUL0262_GUYANDCHICSHAIRSALOON",
      "Latitude": "3.200935",
      "Longitude": "101.710321",
      "Site_Owner": "TM",
      "Existing_New": "Existing",

  },
  {
      "Rollout_Batch": "Batch 4-1",
      "Onboarding_Batch": "Batch 2",
      "Priority": "",
      "Nominal_ID": "KUL_140",
      "Site_ID": "DWKUL0067",
      "Site_Name": "DWKUL0067_PTLGINDAHCONDO",
      "Latitude": "3.066127",
      "Longitude": "101.704114",
      "Site_Owner": "TM",
      "Existing_New": "Existing",

  },
  {
      "Rollout_Batch": "Batch 4-1",
      "Onboarding_Batch": "Batch 2",
      "Priority": "",
      "Nominal_ID": "KUL_127",
      "Site_ID": "DWKUL0056",
      "Site_Name": "DWKUL0056_MEGANSALAKPARK",
      "Latitude": "3.083706",
      "Longitude": "101.701524",
      "Site_Owner": "TM",
      "Existing_New": "Existing",

  },
  {
      "Rollout_Batch": "Batch 4-1",
      "Onboarding_Batch": "Batch 2",
      "Priority": "",
      "Nominal_ID": "KUL_858",
      "Site_ID": "DWKUL0585",
      "Site_Name": "DWKUL0585_ANGGUNPURICONDO",
      "Latitude": "3.17849",
      "Longitude": "101.65422",
      "Site_Owner": "TM",
      "Existing_New": "Existing",

  },
  {
      "Rollout_Batch": "Batch 4-1",
      "Onboarding_Batch": "Batch 2",
      "Priority": "",
      "Nominal_ID": "KUL_520",
      "Site_ID": "DWKUL0358",
      "Site_Name": "DWKUL0358_ARAVILLE",
      "Latitude": "3.13866",
      "Longitude": "101.66442",
      "Site_Owner": "OCK",
      "Existing_New": "Existing",

  },
  {
      "Rollout_Batch": "Batch 4-1",
      "Onboarding_Batch": "Batch 2",
      "Priority": "",
      "Nominal_ID": "SGR_1046",
      "Site_ID": "DBULG1877",
      "Site_Name": "DBULG1877_TMNBKTCHERAS",
      "Latitude": "3.07",
      "Longitude": "101.74938",
      "Site_Owner": "Digi",
      "Existing_New": "Existing",

  },
  {
      "Rollout_Batch": "Batch 4-1",
      "Onboarding_Batch": "Batch 2",
      "Priority": "",
      "Nominal_ID": "KUL_726",
      "Site_ID": "DWKUL0494",
      "Site_Name": "DWKUL0494_APIIT",
      "Latitude": "3.048339",
      "Longitude": "101.692954",
      "Site_Owner": "TM",
      "Existing_New": "Existing",

  },
  {
      "Rollout_Batch": "Batch 4-1",
      "Onboarding_Batch": "Batch 2",
      "Priority": "",
      "Nominal_ID": "KUL_1027",
      "Site_ID": "DWKUL0030",
      "Site_Name": "DWKUL0030_TMNBUKITHIJAUCHERAS",
      "Latitude": "3.08519",
      "Longitude": "101.74143",
      "Site_Owner": "TM",
      "Existing_New": "Existing",

  },
  {
      "Rollout_Batch": "Batch 4-1",
      "Onboarding_Batch": "Batch 2",
      "Priority": "",
      "Nominal_ID": "KUL_334",
      "Site_ID": "DWKUL0224",
      "Site_Name": "DWKUL0224_JLNRAJAMUDA",
      "Latitude": "3.167987",
      "Longitude": "101.7105",
      "Site_Owner": "edotco",
      "Existing_New": "New",

  },
  {
      "Rollout_Batch": "Batch 4-1",
      "Onboarding_Batch": "Batch 2",
      "Priority": "",
      "Nominal_ID": "KUL_835",
      "Site_ID": "DWKUL0561",
      "Site_Name": "DWKUL0561_JLNLEONGYEWKOH",
      "Latitude": "3.146393",
      "Longitude": "101.625522",
      "Site_Owner": "Edotco",
      "Existing_New": "New",

  },
  {
      "Rollout_Batch": "Batch 4-1",
      "Onboarding_Batch": "Batch 2",
      "Priority": "",
      "Nominal_ID": "KUL_411",
      "Site_ID": "DWKUL0284",
      "Site_Name": "DWKUL0284_JLNKGPASIR2",
      "Latitude": "3.104953",
      "Longitude": "101.672798",
      "Site_Owner": "edotco",
      "Existing_New": "New",

  },
  {
      "Rollout_Batch": "Batch 4-1",
      "Onboarding_Batch": "Batch 2",
      "Priority": "",
      "Nominal_ID": "PJY_42",
      "Site_ID": "DWPPJ0879",
      "Site_Name": "DWPPJ0879_WISMATANI",
      "Latitude": "2.91541",
      "Longitude": "101.68327",
      "Site_Owner": "edotco",
      "Existing_New": "Existing",

  },
  {
      "Rollout_Batch": "Batch 4-1",
      "Onboarding_Batch": "Batch 2",
      "Priority": "",
      "Nominal_ID": "PJY_54",
      "Site_ID": "DWPPJ0889",
      "Site_Name": "DWPPJ0889_PREDIPLOMATIC",
      "Latitude": "2.945369",
      "Longitude": "101.723643",
      "Site_Owner": "edotco",
      "Existing_New": "Existing",

  },
  {
      "Rollout_Batch": "Batch 4-1",
      "Onboarding_Batch": "Batch 2",
      "Priority": "",
      "Nominal_ID": "KUL_685",
      "Site_ID": "DWKUL0467",
      "Site_Name": "DWKUL0467_TMNMUTIARARAYA",
      "Latitude": "3.088651",
      "Longitude": "101.740405",
      "Site_Owner": "edotco",
      "Existing_New": "Existing",

  },
  {
      "Rollout_Batch": "Batch 4-1",
      "Onboarding_Batch": "Batch 2",
      "Priority": "",
      "Nominal_ID": "KUL_846",
      "Site_ID": "DWKUL0572",
      "Site_Name": "DWKUL0572_JLNKIARA5",
      "Latitude": "3.167187",
      "Longitude": "101.646885",
      "Site_Owner": "Edotco",
      "Existing_New": "New",

  },
  {
      "Rollout_Batch": "Batch 4-1",
      "Onboarding_Batch": "Batch 2",
      "Priority": "",
      "Nominal_ID": "KUL_866",
      "Site_ID": "DWKUL0593",
      "Site_Name": "DWKUL0593_MONTKIARA",
      "Latitude": "3.170164",
      "Longitude": "101.65881",
      "Site_Owner": "Edotco",
      "Existing_New": "New",

  },
  {
      "Rollout_Batch": "Batch 4-1",
      "Onboarding_Batch": "Batch 2",
      "Priority": "",
      "Nominal_ID": "KUL_473",
      "Site_ID": "DWKUL0324",
      "Site_Name": "DWKUL0324_PLAZAZURICH",
      "Latitude": "3.15149",
      "Longitude": "101.66392",
      "Site_Owner": "Digi",
      "Existing_New": "Existing",

  },
  {
      "Rollout_Batch": "Batch 4-1",
      "Onboarding_Batch": "Batch 2",
      "Priority": "",
      "Nominal_ID": "KUL_524",
      "Site_ID": "DWKUL0361",
      "Site_Name": "DWKUL0361_PANGSAPURIDESATENAGA",
      "Latitude": "3.103212",
      "Longitude": "101.678276",
      "Site_Owner": "Digi",
      "Existing_New": "Existing",

  },
  {
      "Rollout_Batch": "Batch 4-1",
      "Onboarding_Batch": "Batch 2",
      "Priority": "",
      "Nominal_ID": "KUL_252",
      "Site_ID": "DWKUL0155",
      "Site_Name": "DWKUL0155_JLNKUCHINGRT",
      "Latitude": "3.197712",
      "Longitude": "101.672633",
      "Site_Owner": "Digi",
      "Existing_New": "Existing",

  },
  {
      "Rollout_Batch": "Batch 4-1",
      "Onboarding_Batch": "Batch 2",
      "Priority": "",
      "Nominal_ID": "KUL_151",
      "Site_ID": "DWKUL0076",
      "Site_Name": "DWKUL0076_SUPREMEAPT",
      "Latitude": "3.09863",
      "Longitude": "101.74754",
      "Site_Owner": "TM",
      "Existing_New": "Existing",

  },
  {
      "Rollout_Batch": "Batch 4-1",
      "Onboarding_Batch": "Batch 2",
      "Priority": "",
      "Nominal_ID": "KUL_800",
      "Site_ID": "DWKUL0525",
      "Site_Name": "DWKUL0525_BGNGETAHASLI",
      "Latitude": "3.159866",
      "Longitude": "101.711012",
      "Site_Owner": "TM",
      "Existing_New": "Existing",

  },
  {
      "Rollout_Batch": "Batch 4-1",
      "Onboarding_Batch": "Batch 2",
      "Priority": "",
      "Nominal_ID": "KUL_591",
      "Site_ID": "DWKUL0399",
      "Site_Name": "DWKUL0399_JLNIPOHBATU5",
      "Latitude": "3.20129",
      "Longitude": "101.6775",
      "Site_Owner": "edotco",
      "Existing_New": "Existing",

  },
  {
      "Rollout_Batch": "Batch 4-1",
      "Onboarding_Batch": "Batch 2",
      "Priority": "",
      "Nominal_ID": "KUL_242",
      "Site_ID": "DWKUL0149",
      "Site_Name": "DWKUL0149_TMNSRISINAR2(REL)",
      "Latitude": "3.18662",
      "Longitude": "101.65082",
      "Site_Owner": "edotco",
      "Existing_New": "Existing",

  },
  {
      "Rollout_Batch": "Batch 4-1",
      "Onboarding_Batch": "Batch 2",
      "Priority": "",
      "Nominal_ID": "KUL_201",
      "Site_ID": "DWKUL0114",
      "Site_Name": "DWKUL0114_WISMARAMPAI",
      "Latitude": "3.194683",
      "Longitude": "101.731892",
      "Site_Owner": "Digi",
      "Existing_New": "Existing",

  },
  {
      "Rollout_Batch": "Batch 4-1",
      "Onboarding_Batch": "Batch 2",
      "Priority": "",
      "Nominal_ID": "PJY_57",
      "Site_ID": "DWPPJ0892",
      "Site_Name": "DWPPJ0892_KKPDBD3",
      "Latitude": "2.937877",
      "Longitude": "101.704944",
      "Site_Owner": "edotco",
      "Existing_New": "Existing",

  },
  {
      "Rollout_Batch": "Batch 4-1",
      "Onboarding_Batch": "Batch 2",
      "Priority": "",
      "Nominal_ID": "KUL_869",
      "Site_ID": "DWKUL0596",
      "Site_Name": "DWKUL0596_JLNJMBMELAKA2",
      "Latitude": "3.207722",
      "Longitude": "101.658842",
      "Site_Owner": "TM",
      "Existing_New": "Existing",

  },
  {
      "Rollout_Batch": "Batch 4-1",
      "Onboarding_Batch": "Batch 2",
      "Priority": "",
      "Nominal_ID": "KUL_821",
      "Site_ID": "DWKUL0547",
      "Site_Name": "DWKUL0547_SRILANGIT",
      "Latitude": "3.11823",
      "Longitude": "101.682629",
      "Site_Owner": "TM",
      "Existing_New": "Existing",

  },
  {
      "Rollout_Batch": "Batch 4-1",
      "Onboarding_Batch": "Batch 2",
      "Priority": "",
      "Nominal_ID": "PJY_12",
      "Site_ID": "DWPPJ0793",
      "Site_Name": "DWPPJ0793_BLOK8A3APTFASA8",
      "Latitude": "2.936004",
      "Longitude": "101.678334",
      "Site_Owner": "edotco",
      "Existing_New": "Existing",

  },
  {
      "Rollout_Batch": "Batch 4-1",
      "Onboarding_Batch": "Batch 2",
      "Priority": "",
      "Nominal_ID": "PJY_41",
      "Site_ID": "DWPPJ0878",
      "Site_Name": "DWPPJ0878_SURAUALMIZAN",
      "Latitude": "2.93947",
      "Longitude": "101.68367",
      "Site_Owner": "edotco",
      "Existing_New": "Existing",

  },
  {
      "Rollout_Batch": "Batch 4-1",
      "Onboarding_Batch": "Batch 2",
      "Priority": "",
      "Nominal_ID": "PJY_182",
      "Site_ID": "DWPPJ0844",
      "Site_Name": "DWPPJ0844_MENARAZ10",
      "Latitude": "2.93749",
      "Longitude": "101.70817",
      "Site_Owner": "Teleflow",
      "Existing_New": "Existing",

  },
  {
      "Rollout_Batch": "Batch 4-1",
      "Onboarding_Batch": "Batch 2",
      "Priority": "",
      "Nominal_ID": "KUL_530",
      "Site_ID": "DWKUL0364",
      "Site_Name": "DWKUL0364_KGCHERASBARU",
      "Latitude": "3.106389",
      "Longitude": "101.745667",
      "Site_Owner": "Digi",
      "Existing_New": "Existing",

  },
  {
      "Rollout_Batch": "Batch 4-1",
      "Onboarding_Batch": "Batch 2",
      "Priority": "",
      "Nominal_ID": "KUL_1003",
      "Site_ID": "DWKUL0005",
      "Site_Name": "DWKUL0005_JLNMANDARINADAMAI1",
      "Latitude": "3.07757",
      "Longitude": "101.731692",
      "Site_Owner": "Edotco",
      "Existing_New": "New",

  },
  {
      "Rollout_Batch": "Batch 4-1",
      "Onboarding_Batch": "Batch 2",
      "Priority": "",
      "Nominal_ID": "KUL_190",
      "Site_ID": "DWKUL0105",
      "Site_Name": "DWKUL0105_JALANTAR",
      "Latitude": "3.16316",
      "Longitude": "101.69784",
      "Site_Owner": "TM",
      "Existing_New": "Existing",

  },
  {
      "Rollout_Batch": "Batch 4-1",
      "Onboarding_Batch": "Batch 2",
      "Priority": "",
      "Nominal_ID": "KUL_932",
      "Site_ID": "DWKUL0663",
      "Site_Name": "DWKUL0663_STDBUKITJALIL1W",
      "Latitude": "3.055877",
      "Longitude": "101.691329",
      "Site_Owner": "Edotco",
      "Existing_New": "Existing",

  },
  {
      "Rollout_Batch": "Batch 4-1",
      "Onboarding_Batch": "Batch 2",
      "Priority": "",
      "Nominal_ID": "KUL_270",
      "Site_ID": "DWKUL0170",
      "Site_Name": "DWKUL0170_PUBLIKASOLARIS",
      "Latitude": "3.170689",
      "Longitude": "101.66542",
      "Site_Owner": "edotco",
      "Existing_New": "Existing",

  },
  {
      "Rollout_Batch": "Batch 4-1",
      "Onboarding_Batch": "Batch 2",
      "Priority": "",
      "Nominal_ID": "KUL_9",
      "Site_ID": "DWKUL0627",
      "Site_Name": "DWKUL0627_BGNBINTANG",
      "Latitude": "3.1476",
      "Longitude": "101.7113",
      "Site_Owner": "edotco",
      "Existing_New": "Existing",

  },
  {
      "Rollout_Batch": "Batch 4-1",
      "Onboarding_Batch": "Batch 2",
      "Priority": "",
      "Nominal_ID": "KUL_794",
      "Site_ID": "DWKUL0519",
      "Site_Name": "DWKUL0519_LRGCEYLON",
      "Latitude": "3.147192",
      "Longitude": "101.7068",
      "Site_Owner": "edotco",
      "Existing_New": "New",

  },
  {
      "Rollout_Batch": "Batch 4-1",
      "Onboarding_Batch": "Batch 2",
      "Priority": "",
      "Nominal_ID": "KUL_344",
      "Site_ID": "DWKUL0232",
      "Site_Name": "DWKUL0232_BKTDSARA2",
      "Latitude": "3.145839",
      "Longitude": "101.673916",
      "Site_Owner": "edotco",
      "Existing_New": "New",

  },
  {
      "Rollout_Batch": "Batch 4-1",
      "Onboarding_Batch": "Batch 2",
      "Priority": "",
      "Nominal_ID": "KUL_96",
      "Site_ID": "DWKUL0692",
      "Site_Name": "DWKUL0692_NOUVELLEHTL",
      "Latitude": "3.04848",
      "Longitude": "101.706056",
      "Site_Owner": "edotco",
      "Existing_New": "Existing",

  },
  {
      "Rollout_Batch": "Batch 4-1",
      "Onboarding_Batch": "Batch 2",
      "Priority": "",
      "Nominal_ID": "KUL_379",
      "Site_ID": "DWKUL0258",
      "Site_Name": "DWKUL0258_JLNSRIHARTAMAS7",
      "Latitude": "3.157956",
      "Longitude": "101.650183",
      "Site_Owner": "edotco",
      "Existing_New": "Existing",

  },
  {
      "Rollout_Batch": "Batch 4-1",
      "Onboarding_Batch": "Batch 2",
      "Priority": "",
      "Nominal_ID": "KUL_823",
      "Site_ID": "DWKUL0549",
      "Site_Name": "DWKUL0549_BRICKFIELDS",
      "Latitude": "3.13047",
      "Longitude": "101.68645",
      "Site_Owner": "edotco",
      "Existing_New": "Existing",

  },
  {
      "Rollout_Batch": "Batch 4-1",
      "Onboarding_Batch": "Batch 2",
      "Priority": "",
      "Nominal_ID": "KUL_147",
      "Site_ID": "DWKUL0073",
      "Site_Name": "DWKUL0073_JLNAWANDANDAN",
      "Latitude": "3.07038",
      "Longitude": "101.6683",
      "Site_Owner": "TM",
      "Existing_New": "Existing",

  },
  {
      "Rollout_Batch": "Batch 4-1",
      "Onboarding_Batch": "Batch 2",
      "Priority": "",
      "Nominal_ID": "KUL_38",
      "Site_ID": "DWKUL0259",
      "Site_Name": "DWKUL0259_MENARAAA",
      "Latitude": "3.14397",
      "Longitude": "101.72102",
      "Site_Owner": "Digi",
      "Existing_New": "Existing",

  },
  {
      "Rollout_Batch": "Batch 4-1",
      "Onboarding_Batch": "Batch 2",
      "Priority": "",
      "Nominal_ID": "KUL_729",
      "Site_ID": "DWKUL0496",
      "Site_Name": "DWKUL0496_INSTITUTPENGAJIANSISWAZAH",
      "Latitude": "3.124489",
      "Longitude": "101.659475",
      "Site_Owner": "edotco",
      "Existing_New": "Existing",

  },
  {
      "Rollout_Batch": "Batch 4-1",
      "Onboarding_Batch": "Batch 2",
      "Priority": "",
      "Nominal_ID": "KUL_321",
      "Site_ID": "DWKUL0215",
      "Site_Name": "DWKUL0215_JLNDATOSENU30",
      "Latitude": "3.19402",
      "Longitude": "101.69611",
      "Site_Owner": "Digi",
      "Existing_New": "Existing",

  },
  {
      "Rollout_Batch": "Batch 4-1",
      "Onboarding_Batch": "Batch 2",
      "Priority": "",
      "Nominal_ID": "KUL_291",
      "Site_ID": "DWKUL0187",
      "Site_Name": "DWKUL0187_TMNESPLANADE",
      "Latitude": "3.061908",
      "Longitude": "101.675827",
      "Site_Owner": "Digi",
      "Existing_New": "Existing",

  },
  {
      "Rollout_Batch": "Batch 4-1",
      "Onboarding_Batch": "Batch 2",
      "Priority": "",
      "Nominal_ID": "KUL_1025",
      "Site_ID": "DWKUL0029",
      "Site_Name": "DWKUL0029_DESAVILLASCONDO",
      "Latitude": "3.188428",
      "Longitude": "101.73815",
      "Site_Owner": "OCK",
      "Existing_New": "Existing",

  },
  {
      "Rollout_Batch": "Batch 4-1",
      "Onboarding_Batch": "Batch 2",
      "Priority": "",
      "Nominal_ID": "KUL_33",
      "Site_ID": "DWKUL0221",
      "Site_Name": "DWKUL0221_JLNRAJACHULAN",
      "Latitude": "3.14931",
      "Longitude": "101.69944",
      "Site_Owner": "TM",
      "Existing_New": "Existing",

  },
  {
      "Rollout_Batch": "Batch 4-1",
      "Onboarding_Batch": "Batch 2",
      "Priority": "",
      "Nominal_ID": "SGR_852",
      "Site_ID": "DBSEP1842",
      "Site_Name": "DBSEP1842_JLNSILIKON",
      "Latitude": "2.92545",
      "Longitude": "101.64191",
      "Site_Owner": "edotco",
      "Existing_New": "Existing",

  },
  {
      "Rollout_Batch": "Batch 4-1",
      "Onboarding_Batch": "Batch 2",
      "Priority": "",
      "Nominal_ID": "KUL_192",
      "Site_ID": "DWKUL0107",
      "Site_Name": "DWKUL0107_TMNYARL",
      "Latitude": "3.06719",
      "Longitude": "101.66584",
      "Site_Owner": "EdgePoint",
      "Existing_New": "Existing",

  },
  {
      "Rollout_Batch": "Batch 4-1",
      "Onboarding_Batch": "Batch 2",
      "Priority": "",
      "Nominal_ID": "KUL_853",
      "Site_ID": "DWKUL0580",
      "Site_Name": "DWKUL0580_MWEKPGCOMMPARK",
      "Latitude": "3.209134",
      "Longitude": "101.650444",
      "Site_Owner": "Digi",
      "Existing_New": "Existing",

  },
  {
      "Rollout_Batch": "Batch 4-1",
      "Onboarding_Batch": "Batch 2",
      "Priority": "",
      "Nominal_ID": "KUL_177",
      "Site_ID": "DWKUL0095",
      "Site_Name": "DWKUL0095_RESOURCESPRINGAPARTMENT",
      "Latitude": "3.1894",
      "Longitude": "101.71367",
      "Site_Owner": "TM",
      "Existing_New": "Existing",

  },
  {
      "Rollout_Batch": "Batch 4-1",
      "Onboarding_Batch": "Batch 2",
      "Priority": "",
      "Nominal_ID": "KUL_404",
      "Site_ID": "DWKUL0279",
      "Site_Name": "DWKUL0279_ZOLANOFUNITURESTORE",
      "Latitude": "3.08881",
      "Longitude": "101.67387",
      "Site_Owner": "Digi",
      "Existing_New": "Existing",

  },
  {
      "Rollout_Batch": "Batch 4-1",
      "Onboarding_Batch": "Batch 2",
      "Priority": "",
      "Nominal_ID": "KUL_883",
      "Site_ID": "DWKUL0610",
      "Site_Name": "DWKUL0610_JLNSLTNHJAHMADSHAH",
      "Latitude": "3.175188",
      "Longitude": "101.66765",
      "Site_Owner": "Edotco",
      "Existing_New": "New",

  },
  {
      "Rollout_Batch": "Batch 4-1",
      "Onboarding_Batch": "Batch 2",
      "Priority": "",
      "Nominal_ID": "KUL_960",
      "Site_ID": "DWKUL0693",
      "Site_Name": "DWKUL0693_JLNAYERDUSUN",
      "Latitude": "3.191225",
      "Longitude": "101.707996",
      "Site_Owner": "Edotco",
      "Existing_New": "New",

  },
  {
      "Rollout_Batch": "Batch 4-1",
      "Onboarding_Batch": "Batch 2",
      "Priority": "",
      "Nominal_ID": "KUL_987",
      "Site_ID": "DWKUL0721",
      "Site_Name": "DWKUL0721_TMSETAPAKINDAH",
      "Latitude": "3.213982",
      "Longitude": "101.721435",
      "Site_Owner": "Edotco",
      "Existing_New": "New",

  },
  {
      "Rollout_Batch": "Batch 4-1",
      "Onboarding_Batch": "Batch 2",
      "Priority": "",
      "Nominal_ID": "KUL_1029",
      "Site_ID": "DWKUL0032",
      "Site_Name": "DWKUL0032_WangsaMajuSeksyen2",
      "Latitude": "3.207107",
      "Longitude": "101.741088",
      "Site_Owner": "Edotco",
      "Existing_New": "New",

  },
  {
      "Rollout_Batch": "Batch 4-1",
      "Onboarding_Batch": "Batch 2",
      "Priority": "",
      "Nominal_ID": "KUL_125",
      "Site_ID": "DWKUL0055",
      "Site_Name": "DWKUL0055_JLNSERIBINTANG2",
      "Latitude": "3.186996",
      "Longitude": "101.642995",
      "Site_Owner": "Digi",
      "Existing_New": "Existing",

  },
  {
      "Rollout_Batch": "Batch 4-1",
      "Onboarding_Batch": "Batch 2",
      "Priority": "",
      "Nominal_ID": "KUL_156",
      "Site_ID": "DWKUL0079",
      "Site_Name": "DWKUL0079_JLNDTRNVELODROM",
      "Latitude": "3.10941",
      "Longitude": "101.7296",
      "Site_Owner": "Digi",
      "Existing_New": "Existing",

  },
  {
      "Rollout_Batch": "Batch 4-1",
      "Onboarding_Batch": "Batch 2",
      "Priority": "",
      "Nominal_ID": "KUL_132",
      "Site_ID": "DWKUL0060",
      "Site_Name": "DWKUL0060_TMNCHRS",
      "Latitude": "3.100942",
      "Longitude": "101.74142",
      "Site_Owner": "Digi",
      "Existing_New": "Existing",

  },
  {
      "Rollout_Batch": "Batch 4-1",
      "Onboarding_Batch": "Batch 2",
      "Priority": "",
      "Nominal_ID": "KUL_154",
      "Site_ID": "DWKUL0078",
      "Site_Name": "DWKUL0078_BINOVAINDCTR",
      "Latitude": "3.1898",
      "Longitude": "101.6743",
      "Site_Owner": "Digi",
      "Existing_New": "Existing",

  },
  {
      "Rollout_Batch": "Batch 4-1",
      "Onboarding_Batch": "Batch 2",
      "Priority": "",
      "Nominal_ID": "PJY_24",
      "Site_ID": "DWPPJ0863",
      "Site_Name": "DWPPJ0863_JLNP14FPRESINT14",
      "Latitude": "2.95043",
      "Longitude": "101.72076",
      "Site_Owner": "TM",
      "Existing_New": "New",

  },
  {
      "Rollout_Batch": "Batch 4-1",
      "Onboarding_Batch": "Batch 2",
      "Priority": "",
      "Nominal_ID": "PJY_52",
      "Site_ID": "DWPPJ0887",
      "Site_Name": "DWPPJ0887_JALANP11APRESINT10",
      "Latitude": "2.95335",
      "Longitude": "101.69135",
      "Site_Owner": "TM",
      "Existing_New": "New",

  },
  {
      "Rollout_Batch": "Batch 4-1",
      "Onboarding_Batch": "Batch 2",
      "Priority": "",
      "Nominal_ID": "KUL_509",
      "Site_ID": "DWKUL0350",
      "Site_Name": "DWKUL0350_JLN26/26SETAPAKJAYA",
      "Latitude": "3.189604",
      "Longitude": "101.735921",
      "Site_Owner": "edotco",
      "Existing_New": "New",

  },
  {
      "Rollout_Batch": "Batch 4-1",
      "Onboarding_Batch": "Batch 2",
      "Priority": "",
      "Nominal_ID": "PJY_141",
      "Site_ID": "DWPPJ0802",
      "Site_Name": "DWPPJ0802_PJYSNTRL",
      "Latitude": "2.931672",
      "Longitude": "101.6706",
      "Site_Owner": "TM",
      "Existing_New": "New",

  },
  {
      "Rollout_Batch": "Batch 4-1",
      "Onboarding_Batch": "Batch 2",
      "Priority": "",
      "Nominal_ID": "SGR_291",
      "Site_ID": "DBULG1882",
      "Site_Name": "DBULG1882_JALAN8/154",
      "Latitude": "#N/A",
      "Longitude": "#N/A",
      "Site_Owner": "edotco",
      "Existing_New": "New",

  },
  {
      "Rollout_Batch": "Batch 4-1",
      "Onboarding_Batch": "Batch 2",
      "Priority": "",
      "Nominal_ID": "KUL_294",
      "Site_ID": "DWKUL0190",
      "Site_Name": "DWKUL0190_SALAKSELATAN",
      "Latitude": "3.082058",
      "Longitude": "101.692861",
      "Site_Owner": "KJS",
      "Existing_New": "Existing",

  },
  {
      "Rollout_Batch": "Batch 4-1",
      "Onboarding_Batch": "Batch 2",
      "Priority": "",
      "Nominal_ID": "KUL_392",
      "Site_ID": "DWKUL0268",
      "Site_Name": "DWKUL0268_MEDANIDAMAN",
      "Latitude": "3.214351",
      "Longitude": "101.712361",
      "Site_Owner": "edotco",
      "Existing_New": "New",

  },
  {
      "Rollout_Batch": "Batch 4-1",
      "Onboarding_Batch": "Batch 2",
      "Priority": "",
      "Nominal_ID": "KUL_283",
      "Site_ID": "DWKUL0179",
      "Site_Name": "DWKUL0179_TAMANBATUMUDA",
      "Latitude": "3.2251",
      "Longitude": "101.68576",
      "Site_Owner": "Maxis",
      "Existing_New": "Existing",

  },
  {
      "Rollout_Batch": "Batch 4-1",
      "Onboarding_Batch": "Batch 2",
      "Priority": "",
      "Nominal_ID": "SGR_1937",
      "Site_ID": "DWKUL0744",
      "Site_Name": "DWKUL0744_TMNINTANBAIDURI2",
      "Latitude": "3.233341",
      "Longitude": "101.64907",
      "Site_Owner": "edotco",
      "Existing_New": "New",

  },
  {
      "Rollout_Batch": "Batch 4-1",
      "Onboarding_Batch": "Batch 2",
      "Priority": "",
      "Nominal_ID": "KUL_478",
      "Site_ID": "DWKUL0327",
      "Site_Name": "DWKUL0327_TamanSuriaSetapak",
      "Latitude": "3.206042",
      "Longitude": "101.702414",
      "Site_Owner": "Maxis",
      "Existing_New": "Existing",

  },
  {
      "Rollout_Batch": "Batch 4-1",
      "Onboarding_Batch": "Batch 2",
      "Priority": "",
      "Nominal_ID": "KUL_91",
      "Site_ID": "DWKUL0639",
      "Site_Name": "DWKUL0639_WTTMNMELATI",
      "Latitude": "3.2256342",
      "Longitude": "101.7276778",
      "Site_Owner": "Maxis",
      "Existing_New": "Existing",

  },
  {
      "Rollout_Batch": "Batch 4-1",
      "Onboarding_Batch": "Batch 2",
      "Priority": "",
      "Nominal_ID": "KUL_734",
      "Site_ID": "DWKUL0499",
      "Site_Name": "DWKUL0499_CHUNMOTOR",
      "Latitude": "3.19097",
      "Longitude": "101.728285",
      "Site_Owner": "TM",
      "Existing_New": "Existing",

  },
  {
      "Rollout_Batch": "Batch 4-1",
      "Onboarding_Batch": "Batch 2",
      "Priority": "",
      "Nominal_ID": "KUL_1009",
      "Site_ID": "DWKUL0011",
      "Site_Name": "DWKUL0011_JLNREJANG",
      "Latitude": "3.191525",
      "Longitude": "101.731717",
      "Site_Owner": "Edotco",
      "Existing_New": "New",

  },
  {
      "Rollout_Batch": "Batch 4-1",
      "Onboarding_Batch": "Batch 2",
      "Priority": "",
      "Nominal_ID": "SGR_1057",
      "Site_ID": "DBSEP1812",
      "Site_Name": "DBSEP1812_QUILLBLDG3",
      "Latitude": "2.921361",
      "Longitude": "101.653861",
      "Site_Owner": "Maxis",
      "Existing_New": "Existing",

  },
  {
      "Rollout_Batch": "Batch 4-1",
      "Onboarding_Batch": "Batch 2",
      "Priority": "",
      "Nominal_ID": "SGR_1898",
      "Site_ID": "DBSEP1881",
      "Site_Name": "DBSEP1881_PRESINT20",
      "Latitude": "2.885145",
      "Longitude": "101.687436",
      "Site_Owner": "KJS",
      "Existing_New": "Existing",

  },
  {
      "Rollout_Batch": "Batch 4-1",
      "Onboarding_Batch": "Batch 2",
      "Priority": "",
      "Nominal_ID": "PJY_51",
      "Site_ID": "DWPPJ0886",
      "Site_Name": "DWPPJ0886_IPDPUTRAJAYA",
      "Latitude": "2.93227",
      "Longitude": "101.67512",
      "Site_Owner": "Maxis",
      "Existing_New": "Existing",

  },
  {
      "Rollout_Batch": "Batch 4-1",
      "Onboarding_Batch": "Batch 2",
      "Priority": "",
      "Nominal_ID": "Site10365",
      "Site_ID": "DBSEP1847",
      "Site_Name": "DBSEP1847_PSRNBESTARI2",
      "Latitude": "2.92106",
      "Longitude": "101.63821",
      "Site_Owner": "Maxis",
      "Existing_New": "Existing",

  },
  {
      "Rollout_Batch": "Batch 4-1",
      "Onboarding_Batch": "Batch 2",
      "Priority": "",
      "Nominal_ID": "KUL_328",
      "Site_ID": "DWKUL0220",
      "Site_Name": "DWKUL0220_TMNDESASEPUTEH",
      "Latitude": "3.11258",
      "Longitude": "101.68764",
      "Site_Owner": "Maxis",
      "Existing_New": "Existing",

  },
  {
      "Rollout_Batch": "Batch 4-1",
      "Onboarding_Batch": "Batch 2",
      "Priority": "",
      "Nominal_ID": "KUL_193",
      "Site_ID": "DWKUL0108",
      "Site_Name": "DWKUL0108_JLNAWANJAWA",
      "Latitude": "3.075811",
      "Longitude": "101.665749",
      "Site_Owner": "Edotco",
      "Existing_New": "New",

  },
  {
      "Rollout_Batch": "Batch 4-1",
      "Onboarding_Batch": "Batch 2",
      "Priority": "",
      "Nominal_ID": "KUL_937",
      "Site_ID": "DWKUL0668",
      "Site_Name": "DWKUL0668_JLNWANSENDARI",
      "Latitude": "3.068036",
      "Longitude": "101.697911",
      "Site_Owner": "Edotco",
      "Existing_New": "New",

  },
  {
      "Rollout_Batch": "Batch 4-1",
      "Onboarding_Batch": "Batch 2",
      "Priority": "",
      "Nominal_ID": "KUL_1018",
      "Site_ID": "DWKUL0021",
      "Site_Name": "DWKUL0021_ALAMDAMAI",
      "Latitude": "3.058097",
      "Longitude": "101.740615",
      "Site_Owner": "Edotco",
      "Existing_New": "New",

  },
  {
      "Rollout_Batch": "Batch 4-1",
      "Onboarding_Batch": "Batch 2",
      "Priority": "",
      "Nominal_ID": "KUL_1030",
      "Site_ID": "DWKUL0034",
      "Site_Name": "DWKUL0034_TMNBKTANGGERIK",
      "Latitude": "3.065108",
      "Longitude": "101.746294",
      "Site_Owner": "Edotco",
      "Existing_New": "New",

  },
  {
      "Rollout_Batch": "Batch 4-1",
      "Onboarding_Batch": "Batch 2",
      "Priority": "",
      "Nominal_ID": "KUL_907",
      "Site_ID": "DWKUL0636",
      "Site_Name": "DWKUL0636_JALANRUKUN12",
      "Latitude": "3.087909",
      "Longitude": "101.680111",
      "Site_Owner": "Edotco",
      "Existing_New": "New",

  },
  {
      "Rollout_Batch": "Batch 4-1",
      "Onboarding_Batch": "Batch 2",
      "Priority": "",
      "Nominal_ID": "KUL_967",
      "Site_ID": "DWKUL0700",
      "Site_Name": "DWKUL0700_TAMANDESAPETALING",
      "Latitude": "3.082047",
      "Longitude": "101.710981",
      "Site_Owner": "Edotco",
      "Existing_New": "New",

  },
  {
      "Rollout_Batch": "Batch 4-1",
      "Onboarding_Batch": "Batch 2",
      "Priority": "",
      "Nominal_ID": "KUL_1020",
      "Site_ID": "DWKUL0024",
      "Site_Name": "DWKUL0024_JLNDESAAMAN1",
      "Latitude": "3.094176",
      "Longitude": "101.739616",
      "Site_Owner": "Edotco",
      "Existing_New": "New",

  },
  {
      "Rollout_Batch": "Batch 4-1",
      "Onboarding_Batch": "Batch 2",
      "Priority": "",
      "Nominal_ID": "KUL_923",
      "Site_ID": "DWKUL0653",
      "Site_Name": "DWKUL0653_JLNDESABAKTI",
      "Latitude": "3.102905",
      "Longitude": "101.68607",
      "Site_Owner": "Edotco",
      "Existing_New": "New",

  },
  {
      "Rollout_Batch": "Batch 4-1",
      "Onboarding_Batch": "Batch 2",
      "Priority": "",
      "Nominal_ID": "KUL_309",
      "Site_ID": "DWKUL0204",
      "Site_Name": "DWKUL0204_JLNJAMBUGOLOK",
      "Latitude": "3.198083",
      "Longitude": "101.666699",
      "Site_Owner": "edotco",
      "Existing_New": "New",

  },
  {
      "Rollout_Batch": "Batch 4-1",
      "Onboarding_Batch": "Batch 2",
      "Priority": "",
      "Nominal_ID": "KUL_516",
      "Site_ID": "DWKUL0357",
      "Site_Name": "DWKUL0357_JLNAMBONG1",
      "Latitude": "3.212488",
      "Longitude": "101.6487",
      "Site_Owner": "TM",
      "Existing_New": "Existing",

  },
  {
      "Rollout_Batch": "Batch 4-1",
      "Onboarding_Batch": "Batch 2",
      "Priority": "",
      "Nominal_ID": "KUL_541",
      "Site_ID": "DWKUL0370",
      "Site_Name": "DWKUL0370_TITIWANGSA",
      "Latitude": "3.173933",
      "Longitude": "101.711633",
      "Site_Owner": "Maxis",
      "Existing_New": "Existing",

  },
  {
      "Rollout_Batch": "Batch 4-1",
      "Onboarding_Batch": "Batch 2",
      "Priority": "",
      "Nominal_ID": "KUL_189",
      "Site_ID": "DWKUL0103",
      "Site_Name": "DWKUL0103_BKTLANJAN (PAAN)",
      "Latitude": "3.172108",
      "Longitude": "101.61902",
      "Site_Owner": "Maxis",
      "Existing_New": "Existing",

  },
  {
      "Rollout_Batch": "Batch 4-1",
      "Onboarding_Batch": "Batch 2",
      "Priority": "",
      "Nominal_ID": "KUL_950",
      "Site_ID": "DWKUL0682",
      "Site_Name": "DWKUL0682_WSMTATTKHALSA",
      "Latitude": "3.16529",
      "Longitude": "101.700382",
      "Site_Owner": "Maxis",
      "Existing_New": "Existing",

  },
  {
      "Rollout_Batch": "Batch 4-1",
      "Onboarding_Batch": "Batch 2",
      "Priority": "",
      "Nominal_ID": "KUL_868",
      "Site_ID": "DWKUL0595",
      "Site_Name": "DWKUL0595_TMNSRISEGAMBUT1",
      "Latitude": "3.1977446",
      "Longitude": "101.657277",
      "Site_Owner": "Digi",
      "Existing_New": "Existing",

  },
  {
      "Rollout_Batch": "Batch 4-1",
      "Onboarding_Batch": "Batch 2",
      "Priority": "",
      "Nominal_ID": "KUL_719",
      "Site_ID": "DWKUL0490",
      "Site_Name": "DWKUL0490_OPEN UNIVERSITY (OPEN)",
      "Latitude": "3.160159",
      "Longitude": "101.691766",
      "Site_Owner": "Maxis",
      "Existing_New": "Existing",

  },
  {
      "Rollout_Batch": "Batch 4-1",
      "Onboarding_Batch": "Batch 2",
      "Priority": "",
      "Nominal_ID": "KUL_622",
      "Site_ID": "DWKUL0419",
      "Site_Name": "DWKUL0419_SGPENCHALA (MAIL)",
      "Latitude": "3.161138",
      "Longitude": "101.622809",
      "Site_Owner": "Maxis",
      "Existing_New": "Existing",

  },
  {
      "Rollout_Batch": "Batch 4-1",
      "Onboarding_Batch": "Batch 2",
      "Priority": "",
      "Nominal_ID": "KUL_644",
      "Site_ID": "DWKUL0435",
      "Site_Name": "DWKUL0435_WSMYPRTMNSEPUTEH",
      "Latitude": "3.12262",
      "Longitude": "101.68151",
      "Site_Owner": "Maxis",
      "Existing_New": "Existing",

  },
  {
      "Rollout_Batch": "Batch 4-1",
      "Onboarding_Batch": "Batch 2",
      "Priority": "",
      "Nominal_ID": "KUL_186",
      "Site_ID": "DWKUL0101",
      "Site_Name": "DWKUL0101_JALANWANKADIR5",
      "Latitude": "3.140135",
      "Longitude": "101.630577",
      "Site_Owner": "edotco",
      "Existing_New": "New",

  },
  {
      "Rollout_Batch": "Batch 4-1",
      "Onboarding_Batch": "Batch 2",
      "Priority": "",
      "Nominal_ID": "KUL_103",
      "Site_ID": "DWKUL0033",
      "Site_Name": "DWKUL0033_JLNDAMANSARA",
      "Latitude": "3.138183",
      "Longitude": "101.685338",
      "Site_Owner": "edotco",
      "Existing_New": "New",

  },
  {
      "Rollout_Batch": "Batch 4-1",
      "Onboarding_Batch": "Batch 2",
      "Priority": "",
      "Nominal_ID": "KUL_915",
      "Site_ID": "DWKUL0645",
      "Site_Name": "DWKUL0645_JLNRAKYAT",
      "Latitude": "3.130993",
      "Longitude": "101.683",
      "Site_Owner": "Edotco",
      "Existing_New": "New",

  },
  {
      "Rollout_Batch": "Batch 4-1",
      "Onboarding_Batch": "Batch 2",
      "Priority": "",
      "Nominal_ID": "KUL_990",
      "Site_ID": "DWKUL0724",
      "Site_Name": "DWKUL0724_TMNTENAGA",
      "Latitude": "3.111101",
      "Longitude": "101.724566",
      "Site_Owner": "Edotco",
      "Existing_New": "New",

  },
  {
      "Rollout_Batch": "Batch 4-1",
      "Onboarding_Batch": "Batch 2",
      "Priority": "",
      "Nominal_ID": "KUL_885",
      "Site_ID": "DWKUL0612",
      "Site_Name": "DWKUL0612_BUKITKERINCHI",
      "Latitude": "3.106384",
      "Longitude": "101.670342",
      "Site_Owner": "Edotco",
      "Existing_New": "New",

  },
  {
      "Rollout_Batch": "Batch 4-2",
      "Onboarding_Batch": "Batch 2",
      "Priority": "",
      "Nominal_ID": "KUL_289",
      "Site_ID": "DWKUL0185",
      "Site_Name": "DWKUL0185_PUPAWANGSAMAJU",
      "Latitude": "3.204509",
      "Longitude": "101.724995",
      "Site_Owner": "Maxis",
      "Existing_New": "Existing",

  },
  {
      "Rollout_Batch": "Batch 4-2",
      "Onboarding_Batch": "Batch 2",
      "Priority": "",
      "Nominal_ID": "KUL_737",
      "Site_ID": "DWKUL0501",
      "Site_Name": "DWKUL0501_AWANBESAR",
      "Latitude": "3.061401",
      "Longitude": "101.672595",
      "Site_Owner": "VBT",
      "Existing_New": "Existing",

  }
];

var map;
var kmlLayer;
var kmlLayer1;
var kmlLayer2;
var src = '/themes/custom/dnb/kml/IM_CoverageMap_1200_13122021_bot.KMZ';
var src1 = '/themes/custom/dnb/kml/IM_CoverageMap_1200_13122021_mid.KMZ';
var src2 = '/themes/custom/dnb/kml/IM_CoverageMap_1200_13122021_top.KMZ';
var infowindow = new google.maps.InfoWindow();
kmlLayer = new google.maps.KmlLayer(src, {
  suppressInfoWindows: true,
  preserveViewport: true,
  map: map
});
kmlLayer1 = new google.maps.KmlLayer(src1, {
  suppressInfoWindows: true,
  preserveViewport: true,
  map: map
});
kmlLayer2 = new google.maps.KmlLayer(src2, {
  suppressInfoWindows: true,
  preserveViewport: true,
  map: map
});
//MAPS
const googleMpasLatLng = new google.maps.LatLng(2.93527, 101.69112);
const newIconPins = {
  url: "/themes/custom/dnb/img/icon/pin-google-map.svg", // url
  scaledSize: new google.maps.Size(60, 60), // scaled size
  origin: new google.maps.Point(0, 0), // origin
  anchor: new google.maps.Point(15, 15) // anchor //modifed the staging for preview only
};

function init() {
  map = new google.maps.Map(document.getElementById('map_canvas'), {
    zoom: 12,
    center: googleMpasLatLng,
    disableDefaultUI: true,
    mapTypeId: google.maps.MapTypeId.ROADMAP
  });
  kmlLayer.setMap(map);
  kmlLayer1.setMap(map);
  kmlLayer2.setMap(map);
  var myMarker = new google.maps.Marker({
    position: googleMpasLatLng,
    draggable: true,
    icon: newIconPins
  });
  map.setCenter(myMarker.position);
  myMarker.setMap(map);

  var zoomControlDiv = document.createElement('div');
  var zoomControl = new ZoomControl(zoomControlDiv, map);

  zoomControlDiv.index = 1;
  map.controls[google.maps.ControlPosition.RIGHT_BOTTOM].push(zoomControlDiv);

  var searchBox = new google.maps.places.SearchBox(document.getElementById('pac-input'));


  /*$.each(sitesData, function(key, data) {

    var latLng = new google.maps.LatLng(data.Latitude, data.Longitude);

    var marker = new google.maps.Marker({
      position: latLng,
      map: map,
      // icon: icon,
      title: data.Site_Name
    });

    var details = data.Site_Name + ", " + data.Site_Owner + ".";

    bindInfoWindow(marker, map, infowindow, details);

    //    });

  });
  */
  //map.controls[google.maps.ControlPosition.TOP_CENTER].push(document.getElementById('pac-input'));
  google.maps.event.addListener(searchBox, 'places_changed', function () {
    searchBox.set('map', null);
    var places = searchBox.getPlaces();
    var bounds = new google.maps.LatLngBounds();
    var i, place;
    for (i = 0; place = places[i]; i++) {
      (function (place) {
        var marker = new google.maps.Marker({
          position: place.geometry.location,
          icon: newIconPins
        });
        myMarker.setMap(null);
        marker.bindTo('map', searchBox, 'map');
        google.maps.event.addListener(marker, 'map_changed', function () {
          if (!this.getMap()) {
            this.unbindAll();
          }
        });
        bounds.extend(place.geometry.location);


      }(place));

    }
    map.fitBounds(bounds);
    searchBox.set('map', map);
    map.setZoom(Math.min(map.getZoom(), 12));

  });

}
function loadMapLayer(){
  var check = document.getElementById("live5g");
  if (check.checked) {
    kmlLayer.setMap(map);
  } else {
    kmlLayer.setMap(null);
  }
}
function bindInfoWindow(marker, map, infowindow, strDescription) {
  google.maps.event.addListener(marker, 'click', function() {
    infowindow.setContent(strDescription);
    infowindow.open(map, marker);
  });
}
google.maps.event.addDomListener(window, 'load', init);
